### ISSUE TITLE
Cannot connect to nextcloud

### ISSUE THREAD

**Issue by hidenk74** [FrKaram/KS2.Drive#13]
Hi, I've tried with nextcloud 14, but cannot work.
I used http acccess.

**Comment by FrKaram** [comment]
I'll setup a nextcloud server and have a look at this

**Comment by imbmf** [comment]
I am getting this error when i try to mount drive
![drive](https://user-images.githubusercontent.com/5518241/49210552-0e12fe00-f3c6-11e8-8e97-9327391a478f.png)

**Comment by FrKaram** [comment]
Yes, this is an issue with the Webdav layer. I'll dig into it

**Comment by FrKaram** [comment]
I found where the issue was. I can now connect to a NextCloud Server. I'll release an updated version soon

**Comment by FrKaram** [comment]
Nextcloud support has been added in v 0.8.5
