### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dworkin** [FrKaram/KS2.Drive#19]
Is there a license for this project?

WebDAVClient also has no explicit license, but Sagui Itay has effectively released his code into the public domain [issue#26](https://github.com/saguiitay/WebDAVClient/issues/26).

**Comment by FrKaram** [comment]
Hi there, 
that's a good question.
As the software is using WinFSP, it needs to comply with its own licence which state : 

[Software] is distributed under a license that satisfies the Free Software Definition Version 1.141 (https://www.gnu.org/philosophy/free-sw.en.html) or the Open Source Definition Version 1.9 (https://opensource.org/osd).

I do not know exactly which licence(s) are matching those criterias and that is really not on top of my priorities.
In the spirit, whoever can use, modify, redistribute my code as long as it remains open-source.

**Comment by dworkin** [comment]
I see that github.com/saguiitay/WebDAVClient derives from github.com/kvdb/WebDAVClient, which was published under the Creative Commons Zero license.

http://wiki.creativecommons.org/CC0_FAQ

**Comment by dworkin** [comment]
And GPLv3 is mentioned in the About dialog of KS2.Drive, added in commit 48087b28e9c9e61e849fa6a74bed6ff52c4bca95.  All right, that settles it.

**Comment by FrKaram** [comment]
You're right. I completly forgot that I already mentionned GPLV3 in the source.
GPLV3 it is then
