### ISSUE TITLE
Remove KS2.Drive

### ISSUE THREAD

**Issue by FortifiedSA** [FrKaram/KS2.Drive#27]
Hi there how do i completely remove this once installed?

I have made some changes for testing but every time i build application and try install the new build it simply just starts the previous one installed and not the new build. 

KS2.Drive is no where to be found, please can someone assist. 

Kind regards

**Comment by FrKaram** [comment]
Hi

Sorry for the long delay, I was not notified of your question
Have you installed the program via the installer or did you build it from code ?
