### ISSUE TITLE
Support for TLS client certificate authentication

### ISSUE THREAD

**Issue by rmenessec** [FrKaram/KS2.Drive#7]
Would you consider adding the ability to authenticate to HTTPS web servers with client PKI certificates? The servers I run require TLS client certificate authentication as well as a user name and password.

Thanks!

**Comment by FrKaram** [comment]
Hi,
I still have work to do on the basics of the program.
When done, I'll look into it.

**Comment by FrKaram** [comment]
I've setup a server with client certificate authentication. Working on implementing this in KS2 Drive

**Comment by FrKaram** [comment]
Your request has been adressed in v0.8.4 currently available for testing
https://github.com/FrKaram/KS2.Drive/releases/tag/0.8.4

**Comment by rmenessec** [comment]
My WebDAV servers are offline pending upgrades, so it will take me until sometime next week to test.

**Comment by FrKaram** [comment]
no worries. Keep in mind that this program has been tested on Alfresco's webDAV implementation. I cannot guaranty at that point that it will work correctly on another WebDAV server (even though I use a standard WebDAV library)

**Comment by FrKaram** [comment]
I close the issue. Wil be merged in master branch soon
